@host = http://localhost:5000

@productId = 67f94922f814a80491b98ce6


### Create Product Category 
POST {{host}}/api/products/{{productId}}/categories
Content-Type: application/json

{
     "categoryIds": ["661b7f6a5dd33cd51ab2c97b", "661b7f6a5dd33cd51ab2c99c"]
}

### Get all categories of a product
GET {{host}}/api/products/{{productId}}/categories